# Generated by Django 5.0.7 on 2024-08-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Role', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=40)),
            ],
        ),
    ]
